### ISSUE TITLE
As an engineer, I want to get a django, postgres, and postGIS dev server to a basic "Hello, World" state, with instructions in a README for others to follow so that we can all work independently  Heroku and postGIS: https://devcenter.heroku.com/articles/postgis

### ISSUE THREAD

**Issue by benmathes** [TechEquity-Collaborative/Voter-Info#7]
As an engineer, I want to get a django, postgres, and postGIS dev server to a basic "Hello, World" state, with instructions in a README for others to follow so that we can all work independently

Heroku and postGIS: https://devcenter.heroku.com/articles/postgis

**Comment by benmathes** [comment]
made some progress on this last night, some issues w/ pushing with my github credentials on the command line. will debug that next.

**Comment by ericsandine** [comment]
It looks like Mongo has good support for geoJSON as well if Postgress is cumbersome to get up and running, I'm pretty comfortable with MongoDB https://docs.mongodb.com/manual/geospatial-queries/
