### ISSUE TITLE
Enable Julia to load Shapefiles into PostGIS

### ISSUE THREAD

**Issue by wangjoshuah** [TechEquity-Collaborative/Voter-Info#8]
research how to get the gathered spreadsheet data on who is running for which office into our postgres DB

@juliahaha should be able to upload shapefiles for us to query either manually or through an interface.

(Probably just use the django admin interface. Manual and might suck, but data inconsistencies in the spreadsheets might make csv->sql not worth the effort to automate)

**Comment by benmathes** [comment]
FInished this in another PR
